-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 22:58:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina_mecanica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina_mecanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina_mecanica` DEFAULT CHARACTER SET utf8mb4 ;
USE `oficina_mecanica` ;

-- -----------------------------------------------------
-- Table `oficina_mecanica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(150) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `id_cliente` INT NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `idx_veiculo_cliente` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `oficina_mecanica`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `codigo_equipe` INT NULL,
  PRIMARY KEY (`id_equipe`),
  UNIQUE INDEX `codigo_equipe_UNIQUE` (`codigo_equipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`mecanico` (
  `id_mecanico` INT NOT NULL AUTO_INCREMENT,
  `codigo_mecanico` INT NOT NULL,
  `nome_completo` VARCHAR(150) NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `id_equipe` INT NOT NULL,
  PRIMARY KEY (`id_mecanico`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo_mecanico` ASC) VISIBLE,
  INDEX `idx_mecanico_equipe` (`id_equipe` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_equipe`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `oficina_mecanica`.`equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`ordem_servico` (
  `id_ordem_servico` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_entrega` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `data_conclusao` DATE NULL,
  `id_veiculo` INT NOT NULL,
  `id_equipe` INT NOT NULL,
  `autorizado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_ordem_servico`),
  INDEX `idx_os_veiculo` (`id_veiculo` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `idx_os_equipe` (`id_equipe` ASC) VISIBLE,
  CONSTRAINT `fk_os_veiculo`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `oficina_mecanica`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_equipe`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `oficina_mecanica`.`equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`peca` (
  `id_peca` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_peca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`mao_de_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`mao_de_obra` (
  `id_mao_de_obra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `valor_referencia` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_mao_de_obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`servico` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `id_mao_de_obra` INT NOT NULL,
  PRIMARY KEY (`id_servico`),
  INDEX `idx_servico_mao_de_obra` (`id_mao_de_obra` ASC) VISIBLE,
  CONSTRAINT `fk_servico_mao_de_obra`
    FOREIGN KEY (`id_mao_de_obra`)
    REFERENCES `oficina_mecanica`.`mao_de_obra` (`id_mao_de_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`ordem_servico_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`ordem_servico_servico` (
  `id_ordem_servico` INT NOT NULL,
  `id_servico` INT NOT NULL,
  PRIMARY KEY (`id_ordem_servico`, `id_servico`),
  INDEX `idx_os_servico_id_servico` (`id_servico` ASC) VISIBLE,
  INDEX `idx_os_servico_ordem_servico` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_os_servico_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `oficina_mecanica`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_servico_servico`
    FOREIGN KEY (`id_servico`)
    REFERENCES `oficina_mecanica`.`servico` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_mecanica`.`ordem_servico_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_mecanica`.`ordem_servico_peca` (
  `id_ordem_servico` INT NOT NULL,
  `id_peca` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_ordem_servico`, `id_peca`),
  INDEX `idx_os_peca_peca` (`id_peca` ASC) VISIBLE,
  INDEX `idx_os_peca_ordem_servico` (`id_ordem_servico` ASC) VISIBLE,
  CONSTRAINT `fk_os_peca_ordem_servico`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `oficina_mecanica`.`ordem_servico` (`id_ordem_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_peca_peca`
    FOREIGN KEY (`id_peca`)
    REFERENCES `oficina_mecanica`.`peca` (`id_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
