-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 19:38:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce_db` ;

-- -----------------------------------------------------
-- Table `ecommerce_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` CHAR(13) NULL,
  `telefone` CHAR(12) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(50) NULL,
  `cep` CHAR(8) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `padrao` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_endereco`),
  INDEX `idx_endereco_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce_db`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`cliente_PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`cliente_PF` (
  `cpf` CHAR(11) NOT NULL,
  `id_cliente` INT NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_pf_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce_db`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`cliente_PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`cliente_PJ` (
  `cnpj` CHAR(14) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `id_cliente` INT NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_pj_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce_db`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`forma_pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `tipo_pagamento` ENUM('cartão de crédito', 'cartão de débito', 'pix') NOT NULL,
  `detalhes` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `idx_forma_pagamento_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_forma_pagamento_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce_db`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `id_vendedor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `preco_atual` DECIMAL(10,2) NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `idx_produto_fornecedor` (`id_fornecedor` ASC) VISIBLE,
  INDEX `idx_produto_vendedor` (`id_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `ecommerce_db`.`fornecedor` (`id_fornecedor`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_vendedor1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `ecommerce_db`.`vendedor` (`id_vendedor`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pagamento` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `status_pedido` ENUM('processando', 'concluido', 'cancelado') NOT NULL DEFAULT 'processando',
  `data_limite_devolucao` DATE NULL,
  `valor_frete` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id_pedido`),
  INDEX `idx_pedido_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `idx_pedido_endereco` (`id_endereco` ASC) INVISIBLE,
  INDEX `idx_pedido_forma_pagamento` (`id_pagamento` ASC) INVISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce_db`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_endereco`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `ecommerce_db`.`endereco` (`id_endereco`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_forma_pagamento`
    FOREIGN KEY (`id_pagamento`)
    REFERENCES `ecommerce_db`.`forma_pagamento` (`id_pagamento`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`item_pedido` (
  `pedido_id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_vendido` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pedido_id_pedido`, `id_produto`),
  INDEX `idx_pedido_produto_produto` (`id_produto` ASC) VISIBLE,
  INDEX `idx_pedido_produto_pedido` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `ecommerce_db`.`pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `ecommerce_db`.`produto` (`id_produto`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce_db`.`entrega` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `codigo_rastreio` VARCHAR(50) NULL,
  `status_entrega` ENUM('aguardando_coleta', 'em_transporte', 'entregue', 'devolvido') NOT NULL DEFAULT 'aguardando_coleta',
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_entrega`),
  UNIQUE INDEX `idx_entrega_pedido` (`id_pedido` ASC) INVISIBLE,
  CONSTRAINT `fk_entrega_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `ecommerce_db`.`pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
